#!/usr/bin/env python

import os
import sys
import getopt
import textwrap
import logging

import knodat.multimap as kmm

module_logger = logging.getLogger("RAW2SPLOT")
formatter = logging.Formatter(
        fmt = "%(asctime)s -- %(name)s -- %(levelname)s -- %(message)s" )

ch = logging.StreamHandler()
ch.setLevel( logging.WARNING )

module_logger.addHandler( ch )
module_logger.setLevel( logging.WARNING )

def set_debug_level(level):
    possible_levels = dict(debug = logging.DEBUG, info = logging.INFO,
            warning = logging.WARNING, error = logging.ERROR,
            fatal = logging.FATAL)
    ch.setLevel(possible_levels[level])
    module_logger.setLevel(possible_levels[level])

def usage():
    print textwrap.dedent("""\
    Usage: raw2splot [OPTIONS] x y datafilename
    """)

if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ["help", "debug"])

        if ("--help", '') in opts:
            raise getopt.GetoptError("")
        if ("--debug", "") in opts:
            set_debug_level('debug')
            kmm.set_debug_level('debug')

        datafilename = args[2]
        x_col = args[0]
        y_col = args[1]

        data = kmm.MultiMap(datafilename)

        outfilename = datafilename + "_splot"
        
        for opt,val in opts:
            if opt == '-o' or opt == '--outfile':
                outfilename = val

        data.write_file_for_gnuplot_splot(x_col, y_col, outfilename)

    except getopt.GetoptError:
        usage()
           
